# Generated by Django 5.2.6 on 2025-10-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.RenameModel(
            old_name='DeliveryZones',
            new_name='Deliveries',
        ),
    ]
