# Generated by Django 5.2.6 on 2025-11-02 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('commerces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemoptions',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.options'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.dishes'),
        ),
        migrations.AddField(
            model_name='orderitemoptions',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.orderitems'),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.addresses'),
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.restaurants'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpromos',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.orders'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.orders'),
        ),
        migrations.AddField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.orders'),
        ),
        migrations.AddField(
            model_name='orderpromos',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.promos'),
        ),
    ]
