# Generated by Django 5.0 on 2025-10-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
