# Generated by Django 5.0 on 2025-10-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0002_remove_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='active',
            new_name='is_active',
        ),
    ]
