# Generated by Django 5.2.6 on 2025-11-15 11:54

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, help_text="User's email address", max_length=150, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('password', models.CharField(help_text="User's hash representation of the password", max_length=254, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(choices=[('it', 'IT'), ('hr', 'HR'), ('sales', 'SALES'), ('finance', 'Finance')], max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=255)),
                ('birth_date', models.DateField(auto_now=True, verbose_name='Birth date')),
                ('salary', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Salary')),
                ('is_staff', models.BooleanField(default=False, help_text='True if the user is an admin and has an access to the admin panel', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='True if the user is active and has an access to request data', verbose_name='Active status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
