# Generated by Django 5.2.6 on 2025-11-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserabstractuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
