# Generated by Django 5.2.6 on 2025-11-17 18:09

import django.contrib.auth.password_validation
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_customuserabstractuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='The email address of the user', max_length=150, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('password', models.CharField(max_length=254, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='password')),
                ('phone', models.CharField(help_text='The phone number of the user', max_length=20, verbose_name='phone')),
                ('city', models.CharField(help_text='The city of the user', max_length=100, verbose_name='city')),
                ('country', models.CharField(help_text='The country of the user', max_length=100, verbose_name='country')),
                ('department', models.CharField(help_text='The department of the user', max_length=100, verbose_name='department')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=100)),
                ('birth_date', models.DateField(help_text='The birth date of the user', verbose_name='birth date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='The salary of the user', max_digits=10, null=True, verbose_name='salary')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user can log into this admin site.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the user joined the site.', verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, help_text='The date and time the user last logged in.', null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.DeleteModel(
            name='CustomUserAbstractUser',
        ),
    ]
